### ISSUE TITLE
Add health check endpoint for backend

### ISSUE THREAD

**Issue by chriscasto** [metrotranscom/doorway#28] opened 2023-04-04 22:40 UTC
The ALB fronting the backend API needs a health check endpoint that it can ping to make sure the backend is operational and healthy.  Currently it's using the `/jurisdictions` endpoint, but this is probably heavier than needed and may put unnecessary load on the DB and/or backend

**Comment by sarahlazarich** [comment] 2023-07-26 22:08
pull in sooner rather than later

**Comment by sarahlazarich** [comment] 2023-08-11 21:16
dupe of https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/256

**Closed by sarahlazarich** 2023-08-11 21:16 UTC
Labels: validated
